using Content.Client.UserInterface.Controls;
using Content.Shared.Salvage.Expeditions;
using Content.Shared._NF.Bank;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.Salvage.UI;

[GenerateTypedNameReferences]
public sealed partial class ExpeditionDiskPrinterMenu : FancyWindow
{
    public event Action<string>? OnPrintRequested;

    public ExpeditionDiskPrinterMenu()
    {
        RobustXamlLoader.Load(this);
    }

    public void Update(ExpeditionDiskPrinterBoundUserInterfaceState state)
    {
        DifficultyContainer.Children.Clear();

        foreach (var entry in state.Difficulties)
        {
            var difficultyName = Loc.GetString($"salvage-expedition-difficulty-{entry.DifficultyId}");
            var costText = BankSystemExtensions.ToSpesoString(entry.Cost);
            var button = new Button
            {
                Text = Loc.GetString("expedition-disk-printer-print", ("number", entry.Number), ("difficulty", difficultyName), ("cost", costText)),
                HorizontalAlignment = HAlignment.Left,
                MinWidth = 300,
            };

            var difficultyId = entry.DifficultyId;
            button.OnPressed += _ => OnPrintRequested?.Invoke(difficultyId);
            DifficultyContainer.AddChild(button);
        }
    }
}
